---
- pip: name=supervisor

- group: name={{supervisor_user_group}} state=present

- user: name={{item}} groups={{supervisor_user_group}} append=yes
  with_items: '{{supervisor_group_users}}'

- file: path="{{supervisor_conf_dir}}"
    state=directory
    owner="{{supervisor_user}}"
    group="{{supervisor_user_group}}"
    mode="ug=rwx,o=rx"

- template: src=supervisord.conf dest="{{supervisor_config}}"

- template: src=supervisor_initd dest=/etc/init.d/supervisor mode=0755
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and supervisor_init_scripts

- shell: update-rc.d supervisor defaults
  register: result
  changed_when: "result.rc != 0"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and supervisor_init_scripts

- file: path="{{supervisor_log_dir}}" state=directory

- file: path="{{supervisor_conf_dir}}" state=directory

# starting a service can fail due downstream configurations not being in order yet; this should be a notify?
- service: name=supervisor enabled=yes state=started
  ignore_errors: True
